id: generic-quickstart-id-2
slug: quickstart-slug
description: |
  ## What is Generic Quickstart?

  Free generic quickstart distribution built to be compatible with Test Suite Enterprise.

  ## Get started!

  Choose this quickstart and follow New Relic's guided install process to monitor your generic technology environment.


## Missing fields ##

# summary: |
#  Use the New Relic Infrastructure agent to monitor something
# icon: logo.svg

level: New Relic
authors:
  - New Relic
title: Generic Quickstart
keywords:
  - os
  - operating system

installPlans:
  - guided-install
