name: Clear website cache

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  clear-cache:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.WEBSITE_CACHE_TOKEN }}
    steps:
      - name: Clear HTML
        run: |
          curl -X PURGE -H "Accept: application/json" -H "Fastly-Key: $TOKEN" -H "host: newrelic.com" --location "https://newrelic.com/instant-observability"

      - name: Clear page data
        run: |
          curl -X PURGE -H "Accept: application/json" -H "Fastly-Key: $TOKEN" -H "host: newrelic.com" --location "https://newrelic.com/instant-observability/page-data/index/page-data.json"

